# Use the parent image from tensorflow (Ubuntu 16.04. + CUDA 10 + Python 3.5 + TensorFlow 1.13.1 + Jupyter notebook already installed
FROM tensorflow/tensorflow:1.13.1-jupyter

MAINTAINER kaland

RUN apt update --fix-missing
RUN apt install -y libopenmpi-dev ssh sudo nano gcc cmake git
RUN apt install -y build-essential freeglut3 freeglut3-dev libxi-dev libxmu-dev zlib1g-dev
RUN apt install -y xvfb python3-tk python-opengl
RUN apt install -y swig python-box2d
# RUN apt install -y x11vnc 

RUN pip install --upgrade pip
RUN pip install mpi4py pympler cma
RUN pip install gym 
RUN pip install box2d-py
RUN pip install gym[box2d]
RUN pip install gym[atari]
RUN pip install scikit-image
RUN pip install matplotlib
RUN pip install jupyterlab

COPY ./DockerSetup/jupyter_notebook_config.py /root/.jupyter/jupyter_notebook_config.py
COPY ./Scripts /tf/UserScripts

RUN echo "PermitRootLogin yes\nSubsystem sftp internal-sftp" > /etc/ssh/sshd_config
RUN echo "root:init" | chpasswd

WORKDIR /tf

# CMD service ssh start
# CMD jupyter lab

CMD bash
